### ISSUE TITLE
scrivito_in_editable_view 

### ISSUE THREAD

**Issue by FEwaldIP** [Scrivito/scrivito_section_widgets#1]
![bildschirmfoto 2015-06-11 um 14 16 05](https://cloud.githubusercontent.com/assets/5861537/8106765/82a9c910-1044-11e5-919a-dcb40960d050.png)

Man kann außerhalb des scrivito_in_editable_view keine scrivito Funktionen aufrufen.

**Comment by gertimon** [comment]
This Issue was fixed but issue was not closed.
